# Generated by Django 3.1.7 on 2021-03-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='pizza',
            field=models.ForeignKey(default=10.5, on_delete=django.db.models.deletion.CASCADE, to='order.pizza'),
            preserve_default=False,
        ),
    ]
