# Generated by Django 3.1.7 on 2021-03-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210316_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='pizza',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='order.pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize', to='order.prize'),
        ),
    ]
