# Generated by Django 3.1.7 on 2021-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210316_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='prizeL',
            new_name='prize',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='prizeM',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='prizeS',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.ManyToManyField(null=True, to='order.Prize'),
        ),
    ]
