# Generated by Django 3.1.7 on 2021-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210316_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='prize',
            field=models.ManyToManyField(to='order.Prize'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, to='order.Topping'),
        ),
    ]
