# Generated by Django 3.1.7 on 2021-03-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210317_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=30)),
                ('head2', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
