# Generated by Django 3.1.7 on 2021-03-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210318_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
