# Generated by Django 3.1.7 on 2021-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=30)),
                ('head2', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
