# Generated by Django 3.1.7 on 2021-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(default='images/gallery-img1.jpg', upload_to='images/about'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='thumbnail',
            field=models.ImageField(default='images/gallery-img1.jpg', upload_to='images/pizza'),
        ),
    ]
