# Generated by Django 3.1.7 on 2021-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210318_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
