# Generated by Django 3.1.7 on 2021-03-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_contact_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prizesize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='prizesize',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pizza'),
        ),
    ]
