# Generated by Django 3.1.7 on 2021-03-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210319_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizesize',
            options={'verbose_name_plural': 'Pizza Prizes & Sizes'},
        ),
    ]
