# Generated by Django 3.1.7 on 2021-03-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20210319_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizesize',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.category'),
        ),
    ]
