# Generated by Django 3.1.7 on 2021-03-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_prizesize_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='prizesize',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.prize'),
        ),
        migrations.AlterField(
            model_name='prizesize',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.size'),
        ),
    ]
