# Generated by Django 3.1.7 on 2021-03-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20210319_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='thumbnail',
            field=models.ImageField(default='media_root/images/gallery-img1.jpg', upload_to='images/pizza'),
        ),
        migrations.AlterField(
            model_name='prizesize',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.category'),
        ),
        migrations.AlterField(
            model_name='prizesize',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.prize'),
        ),
        migrations.AlterField(
            model_name='prizesize',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.size'),
        ),
    ]
