# Generated by Django 3.1.7 on 2021-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20210319_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
